# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e6f13c4ef853542e232387f3760340b915012f0e82b7abdc1a4ee0926870a939506c1f1e975617b0c10f48643ca3f78501ddcec2482d4ca53a0aab0d3724860

test:
  secret_key_base: 2952e1d9b0b5af8e640076df19ad760b617c67237df98bcc42646d9a6bf7087c5c84b1ecf3ab06c71e157082367c949c32f494c74db427c632093b0b2b89820f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
